### ISSUE TITLE
Add license badge in the repo

### ISSUE THREAD

**Issue by fgcjobzi** [Jobzi-Artificial-Intelligence/ziconnect-app-angular#97]
**Is your feature request related to a problem? Please describe.**
Add a badge for better visualization and classification of the license type

**Describe the solution you'd like**
Add the information in the readme file description

**Describe alternatives you've considered**
Not applicable

**Additional context**
Not applicable

**Comment by fgcjobzi** [comment]
Hello @Soumya-Kushwaha, would you like to work on this task also? This is the last one you performed in another repo.
Thanks in advance.

**Comment by Soumya-Kushwaha** [comment]
I'd love to do this. Thanks!

**Comment by fgcjobzi** [comment]
> I'd love to do this. Thanks!

Assigned for you @Soumya-Kushwaha !
Thanks in advance.
